export const appCopy = {
  portalLabel: "Portal",
  greeting: (name: string) => (name ? `Halo, ${name}` : "Halo"),
  portalDescription: "Pilih modul untuk mulai bekerja.",
  modulesTitle: "Modul",
  continueTitle: "Lanjutkan",
  continueEmptyTitle: "Belum ada hasil",
  continueEmptyBody: "Tiga hasil terakhirmu dari semua modul akan muncul di sini.",
  topUp: "Top-up",
  topUpSoon: "Top-up segera hadir",
  credit: {
    label: "Saldo kredit",
    unavailable: "Saldo segera",
    unavailableHint: "Saldo kredit aktif saat sistem kredit dibuka.",
  },
  nav: {
    main: "Navigasi aplikasi",
    openMenu: "Buka menu",
    menuTitle: "Menu",
    modules: "Modul",
    library: "Library",
    credits: "Kredit",
    breadcrumb: "Breadcrumb",
  },
  account: {
    menu: "Menu akun",
    signOut: "Keluar",
  },
  copy: {
    label: "Salin",
    done: "Tersalin",
    success: "Tersalin ke clipboard.",
    failed: "Gagal menyalin. Salin manual dari halaman ini.",
  },
  library: {
    metaTitle: "Library",
    title: "Library",
    description: "Semua hasil yang sudah kamu buat, dari semua modul.",
    filterLabel: "Filter modul",
    all: "Semua",
    untitled: "Tanpa judul",
    open: "Buka",
    delete: "Hapus",
    deleteTitle: "Hapus hasil ini?",
    deleteBody: "Hasil akan dihapus permanen dari Library dan tidak bisa dikembalikan.",
    deleteConfirm: "Ya, hapus",
    cancel: "Batal",
    deleted: "Hasil dihapus.",
    deleteFailed: "Gagal menghapus hasil. Coba lagi.",
    emptyTitle: "Belum ada hasil",
    emptyBody: "Hasil yang kamu buat di modul mana pun akan tersimpan otomatis di sini.",
    emptyFilteredBody: "Belum ada hasil dari modul ini.",
    emptyCta: "Coba PRD Mini",
  },
  credits: {
    metaTitle: "Kredit",
    title: "Kredit",
    description: "Saldo dan riwayat pemakaian kreditmu.",
    balanceLabel: "Saldo saat ini",
    topUpTitle: "Isi saldo",
    topUpBody: "Top-up lewat QRIS, virtual account, dan e-wallet sedang disiapkan.",
    historyTitle: "Riwayat",
    columns: { date: "Waktu", description: "Keterangan", amount: "Kredit" },
    emptyTitle: "Belum ada riwayat",
    emptyBody: "Setiap penambahan dan pemakaian kredit akan tercatat di sini.",
    reasons: {
      signup_bonus: "Bonus pendaftaran",
      topup: "Top-up",
      spend: "Pemakaian",
      refund: "Pengembalian",
      admin: "Penyesuaian",
    },
  },
  workspace: {
    inputTab: "Input",
    resultTab: "Hasil",
    inputTitle: "Input",
    resultTitle: "Hasil",
    soonTitle: "Modul ini segera hadir",
    soonBody: "Form untuk modul ini sedang disiapkan. Pantau statusnya di portal.",
    resultEmptyTitle: "Belum ada hasil",
    resultEmptyBody: "Hasil dari modul ini akan tampil di sini.",
    backToPortal: "Kembali ke portal",
  },
} as const;
