import { brand } from "@/config/brand";

export const authCopy = {
  fields: {
    name: "Nama",
    email: "Email",
    password: "Kata sandi",
    newPassword: "Kata sandi baru",
    passwordHint: "Minimal 8 karakter.",
  },
  google: "Lanjutkan dengan Google",
  or: "atau",
  signIn: {
    metaTitle: "Masuk",
    title: "Masuk ke akunmu",
    description: "Lanjutkan pekerjaanmu di portal.",
    submit: "Masuk",
    forgot: "Lupa kata sandi?",
    switchText: "Belum punya akun?",
    switchLink: "Daftar gratis",
  },
  signUp: {
    metaTitle: "Daftar",
    title: "Buat akun gratis",
    description: `Dapatkan ${brand.signupBonusCredits} kredit untuk mencoba.`,
    submit: "Daftar",
    checkEmail: "Cek email kamu dan klik tautan konfirmasi untuk mengaktifkan akun.",
    terms: "Dengan mendaftar, kamu menyetujui",
    termsLink: "Syarat Layanan",
    and: "dan",
    privacyLink: "Kebijakan Privasi",
    switchText: "Sudah punya akun?",
    switchLink: "Masuk",
  },
  forgot: {
    metaTitle: "Lupa kata sandi",
    title: "Atur ulang kata sandi",
    description: "Masukkan email akunmu. Kami kirim tautan untuk membuat kata sandi baru.",
    submit: "Kirim tautan",
    sent: "Jika email itu terdaftar, tautan atur ulang sudah dikirim. Cek kotak masuk dan folder spam.",
    back: "Kembali ke halaman masuk",
  },
  reset: {
    metaTitle: "Kata sandi baru",
    title: "Buat kata sandi baru",
    description: "Masukkan kata sandi baru untuk akunmu.",
    submit: "Simpan kata sandi",
  },
  signOut: "Keluar",
  errors: {
    invalidEmail: "Masukkan alamat email yang valid.",
    nameRequired: "Nama wajib diisi.",
    passwordTooShort: "Kata sandi minimal 8 karakter.",
    passwordRequired: "Kata sandi wajib diisi.",
    invalidCredentials: "Email atau kata sandi salah.",
    emailNotConfirmed: "Email belum dikonfirmasi. Cek kotak masukmu.",
    userExists: "Email ini sudah terdaftar. Silakan masuk.",
    weakPassword: "Kata sandi terlalu lemah. Coba yang lebih panjang.",
    rateLimited: "Terlalu banyak percobaan. Tunggu sebentar lalu coba lagi.",
    samePassword: "Kata sandi baru harus berbeda dari yang lama.",
    callback: "Tautan tidak valid atau sudah kedaluwarsa. Silakan coba lagi.",
    oauth: "Gagal masuk dengan Google. Coba lagi.",
    generic: "Terjadi kesalahan. Coba lagi sebentar lagi.",
  },
} as const;
